{
  "name": "RPA065ErrorAndExceptionManagement_06Practice02GlobalHandler",
  "projectId": "7350b2a9-f87a-4f25-93c6-929dbe8e6797",
  "description": "Problem Statement: Use the global exception handler to handle exceptions not caught by Try to Catch activities",
  "main": "Main.xaml",
  "dependencies": {
    "UiPath.Excel.Activities": "[2.22.3]",
    "UiPath.Mail.Activities": "[1.21.1]",
    "UiPath.System.Activities": "[23.10.3]",
    "UiPath.Testing.Activities": "[23.10.0]",
    "UiPath.UIAutomation.Activities": "[23.10.7]"
  },
  "webServices": [],
  "entitiesStores": [],
  "schemaVersion": "4.0",
  "studioVersion": "23.10.2.0",
  "projectVersion": "1.0.0",
  "runtimeOptions": {
    "exceptionHandlerWorkflow": "GlobalHandler.xaml",
    "autoDispose": false,
    "netFrameworkLazyLoading": false,
    "isPausable": true,
    "isAttended": false,
    "requiresUserInteraction": true,
    "supportsPersistence": false,
    "workflowSerialization": "DataContract",
    "excludedLoggedData": [
      "Private:*",
      "*password*"
    ],
    "executionType": "Workflow",
    "readyForPiP": false,
    "startsInPiP": false,
    "mustRestoreAllDependencies": true,
    "pipType": "ChildSession"
  },
  "designOptions": {
    "projectProfile": "Developement",
    "outputType": "Process",
    "libraryOptions": {
      "includeOriginalXaml": false,
      "privateWorkflows": []
    },
    "processOptions": {
      "ignoredFiles": []
    },
    "fileInfoCollection": [],
    "modernBehavior": true,
    "saveToCloud": false
  },
  "expressionLanguage": "VisualBasic",
  "entryPoints": [
    {
      "filePath": "Main.xaml",
      "uniqueId": "807a56fa-9a3b-497d-838d-ef2e9ba80006",
      "input": [],
      "output": []
    }
  ],
  "isTemplate": false,
  "templateProjectData": {},
  "publishData": {},
  "targetFramework": "Windows"
}